### ISSUE TITLE
HTTPS configuration: "Your connection is not private"

### ISSUE THREAD

**Issue by nelsonblaha** [SlickRailsDevelopment/tabislick#12]
"Incomplete" HTTPS setup causes a potentially-scary message when https://www.tabislick.com is visited in Chrome. Possible to proceed only by assuring Chrome that you know what you're doing by visiting.

<img width="1280" alt="screenshot 2016-02-11 10 35 11" src="https://cloud.githubusercontent.com/assets/1343167/12982676/6eee5d8c-d0ab-11e5-97ae-fc68db5a8fb4.png">

**Comment by tabislick** [comment]
I must have copied the link incorrectly. Now the link should match and not bring up that error. Let me

**Comment by nelsonblaha** [comment]
Much better! No more chrome warning wall, but https is still invalid, btw:
<img width="1280" alt="screenshot 2016-02-11 15 50 37" src="https://cloud.githubusercontent.com/assets/1343167/12991975/5743aa44-d0d7-11e5-97e6-2c34c46e96c8.png">

**Comment by nelsonblaha** [comment]
Personally, I'd just stick to http://www.tabislick.com. I only visited https because I clicked the link on github. It's not like you're a bank or anything. Devin would know for sure, but my understanding is that you gotta pay a cert authority a bunch to get the nice green https stuff. The site looks great, by the way!

**Comment by tabislick** [comment]
Ahh OK. Yeah I thought that might be the case. Thanks!
